service: dance-academy-backend

app: dance-academy
org: remusrd

frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  batch-user-creation:
    handler: bin/batch-user-creation
    memorySize: 128
    environment:
      TABLE_NAME: luna-salcedo
  attendance-clearance:
    handler: bin/attendance-clearance
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action: dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:eu-west-2:*:*
    memorySize: 128
    environment:
      TABLE_NAME: luna-salcedo