service: dance-academy-backend

app: dance-academy
org: remusrd

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  batch-user-creation:
    handler: batch-user-creation
  attendance-clerance:
    handler: attendance-clearance