service: dance-academy-backend

app: dance-academy
org: remusrd

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  batch-user-creation:
    handler: bin/batch-user-creation
    memorySize: 128
    environment:
      TABLE_NAME: luna-salcedo
  attendance-clerance:
    handler: bin/attendance-clearance
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        action:
          - 'dynamodb:UpdateItem'
    memorySize: 128
    environment:
      TABLE_NAME: luna-salcedo