name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy dev
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build lambdas
      uses: cedrickring/golang-action@1.4.1
    - name: Install serverless per role plugin
      run: npm i serverless-iam-roles-per-function
    - name: Install serverless pseudo-parameters plugin
      run: npm i serverless-pseudo-parameters
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --verbose
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
